import { mkdir, readdir, readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import { buildDossiersFromResearch } from "../src/lib/dossier/build-from-research";
import type { SpendingProject } from "../src/data/projects";
import type { RawDossierResearch } from "../src/lib/research/types";

async function main() {
  const rawDir = path.join(process.cwd(), "src", "data", "raw");
  const generatedDir = path.join(process.cwd(), "src", "data", "generated");
  const rawPath = await findLatestRawResearchFile(rawDir);

  if (!rawPath) {
    throw new Error(`No raw research files found in ${rawDir}`);
  }

  console.log(`[dossier] reading ${rawPath}`);

  const raw = JSON.parse(await readFile(rawPath, "utf8")) as RawDossierResearch;
  const datePart = extractDatePart(rawPath) ?? new Date().toISOString().slice(0, 10);
  const generatedAt = new Date(`${datePart}T00:00:00.000Z`);
  const dossiers = buildDossiersFromResearch(raw, { generatedAt });

  await mkdir(generatedDir, { recursive: true });

  const outPath = path.join(generatedDir, `piacenza-dossiers-${datePart}.ts`);
  const output = renderTypeScriptOutput(dossiers);
  await writeFile(outPath, output, "utf8");
  const latestPath = path.join(generatedDir, "piacenza-dossiers-latest.ts");
  await writeFile(latestPath, output, "utf8");

  console.log(`[dossier] wrote ${outPath}`);
  console.log(`[dossier] wrote ${latestPath}`);
  console.log(`[dossier] dossiers=${dossiers.length}`);
}

async function findLatestRawResearchFile(rawDir: string) {
  const entries = await readdir(rawDir, { withFileTypes: true }).catch(() => []);
  const files = entries
    .filter((entry) => entry.isFile())
    .map((entry) => entry.name)
    .filter((name) => /^piacenza-research-\d{4}-\d{2}-\d{2}\.json$/.test(name))
    .sort();

  const latest = files.at(-1);
  return latest ? path.join(rawDir, latest) : null;
}

function renderTypeScriptOutput(dossiers: SpendingProject[]) {
  return `import type { SpendingProject } from "../projects";

// Generated by scripts/build-dossiers-from-research.ts.
// Review manually before merging into projects.ts.
export const generatedPiacenzaDossiers = ${JSON.stringify(dossiers, null, 2)} satisfies SpendingProject[];
`;
}

function extractDatePart(filePath: string) {
  return /piacenza-research-(\d{4}-\d{2}-\d{2})\.json$/.exec(path.basename(filePath))?.[1] ?? null;
}

main().catch((error) => {
  console.error("[dossier] failed", error);
  process.exitCode = 1;
});
